import fs from 'node:fs';
import sharp from '/Users/lucka/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp/dist/index.mjs';
process.chdir(new URL('./',import.meta.url).pathname);
const old='../2026-09-22-kambariai/',root='https://raw.githubusercontent.com/elaiskai/pro7-email-assets/main/2026-09-25-super-cleaner/';
const url='https://www.pro7.lt/svaros-prekes/113-americol-super-cleaner-0-75-l-universalus-valiklis-koncentratas';
const pairs=[['chairs','Minkštiems baldams','Dėmėms ant valomų sofos ir kėdžių audinių.'],['sneakers','Batams','Kai ant šviesių kedukų matosi kiekvienas pasivaikščiojimas.'],['wall','Sienoms','Nešvarumams aplink jungiklius, jei sienos danga tinkama valyti.'],['board','Lentoms','Rašymo žymėms nuo valomų lentų paviršių.'],['car-seat','Automobilio salonui','Nešvarumams ant sėdynių audinio.'],['window','Langų rėmams','Susikaupusiam purvui nuo plaunamų rėmų.']];
fs.copyFileSync(old+'logo-safe.png','logo-safe.png');
fs.copyFileSync(old+'super-packshot.jpg','super-packshot.jpg');
const frames=[];
for(const [key,title] of pairs.filter(p=>['sneakers','wall','car-seat'].includes(p[0]))){
 const svg=Buffer.from(`<svg width="600" height="350" xmlns="http://www.w3.org/2000/svg"><rect width="600" height="350" fill="white"/><text x="24" y="28" font-family="Arial" font-size="19" font-weight="700" fill="#183127">${title}</text><text x="24" y="334" font-family="Arial" font-size="12" font-weight="700" fill="#183127">PRIEŠ</text><text x="306" y="334" font-family="Arial" font-size="12" font-weight="700" fill="#183127">PO</text></svg>`);
 const frame=await sharp(svg).composite([{input:await sharp(key+'-before.jpg').resize(270,270,{fit:'contain',background:'white'}).toBuffer(),left:24,top:42},{input:await sharp(key+'-after.jpg').resize(270,270,{fit:'contain',background:'white'}).toBuffer(),left:306,top:42}]).png().toBuffer();
 frames.push(frame);await sharp(frame).png().toFile('hero-'+key+'.png');
}
await sharp(frames,{join:{animated:true}}).gif({delay:[1300,1300,1300],loop:0,colours:128}).toFile('hero-results.gif');
const image=(f,alt,w=552)=>`<a href="${url}"><img src="${root+f}" alt="${alt}" width="${w}" style="display:block;width:100%;max-width:${w}px;height:auto;border:0"></a>`;
const row=(s,p='0 24px')=>`<tr><td bgcolor="#ffffff" style="padding:${p};background:#ffffff">${s}</td></tr>`;
const cta=()=>`<a class="cta" href="${url}" style="display:block;background:#42ba7d;color:#183127;text-align:center;text-decoration:none;font-size:15px;font-weight:700;line-height:22px;padding:14px 12px;border-radius:4px">Rinktis SUPER CLEANER</a>`;
let b=row('<p style="margin:0;color:#ffffff;font-size:10px;font-weight:700;line-height:18px;text-align:center">📦 NEMOKAMAS PRISTATYMAS LIETUVOJE NUO 45 € 📦</p>','8px 12px').replace('bgcolor="#ffffff"','bgcolor="#42ba7d"').replace('background:#ffffff','background:#42ba7d');
b+=row(`<table role="presentation" width="100%"><tr><td width="100"><a href="https://www.pro7.lt/"><img src="${root}logo-safe.png" alt="PRO7" width="96" style="display:block;width:96px;height:auto"></a></td><td align="right" style="font-size:10px;font-weight:700"><a href="https://www.pro7.lt/svaros-prekes-valikliai" style="color:#183127;text-decoration:none;padding:12px 3px">VALIKLIAI</a> <a href="https://www.pro7.lt/akcijos-pasiulymai" style="color:#183127;text-decoration:none;padding:12px 3px">AKCIJOS</a></td></tr></table>`,'14px 24px');
b+=row(image('hero-frame-v3.jpg','Švara netelpa į vieną kambarį. SUPER CLEANER baldams, batams ir plaunamiems paviršiams.',600),'0');
b+=row('<p style="font-size:15px;line-height:1.65;margin:0 0 12px">Sveiki,</p><p style="font-size:15px;line-height:1.65;margin:0">Dėmė ant kėdės, nešvarūs kedukai, apsitaškęs paviršius. Ne kiekvienam darbui reikia atskiro buteliuko.</p>','12px 24px 20px');
b+=row('<p style="font-size:15px;line-height:1.65;margin:0">SUPER CLEANER yra universalus valiklis baldų audiniams, batams ir plaunamiems paviršiams. Žemiau matote jo valymo rezultatus.</p>','0 24px 12px');
b+=row(image('hero-results.gif','SUPER CLEANER: batų, sienos ir automobilio sėdynės valymo rezultatai',600),'0');
for(const [i,[key,title,desc]] of pairs.entries()){
 b+=row(`<div style="border-top:1px solid #dfe7e2;padding:18px 0 12px"><h2 style="font-size:21px;line-height:1.3;margin:0 0 6px"><span style="color:#26744d;font-size:13px">0${i+1}</span> ${title}</h2><p style="font-size:14px;line-height:1.5;margin:0">${desc}</p></div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="table-layout:fixed"><tr><td width="50%" style="padding-right:3px">${image(key+'-before.jpg',title+', prieš valymą',273)}</td><td width="50%" style="padding-left:3px">${image(key+'-after.jpg',title+', po valymo',273)}</td></tr><tr><td style="padding-top:7px;font-size:10px;font-weight:700;letter-spacing:1px">PRIEŠ</td><td style="padding-top:7px;font-size:10px;font-weight:700;letter-spacing:1px">PO</td></tr></table>`,'0 24px 22px');
}
b+=row('<p style="font-size:11px;line-height:1.6;color:#52635a;margin:0">Prieš valydami patikrinkite priemonės tinkamumą ir išbandykite mažai matomoje vietoje. Laikykitės etiketės ir paviršiaus gamintojo nurodymų. Nuotraukose pateikti konkretūs valymo pavyzdžiai.</p>','0 24px 24px');
b+=row(`<div style="border-top:2px solid #42ba7d;padding-top:24px;text-align:center"><p style="font-size:11px;letter-spacing:1px;font-weight:700;margin:0 0 8px">VISIEMS ŠIEMS DARBAMS</p><h2 style="font-size:26px;margin:0 0 6px">SUPER CLEANER</h2><p style="font-size:14px;margin:0">Universalus valiklis, 750 ml</p><table role="presentation" align="center" width="100%" style="max-width:340px;margin:0 auto"><tr><td>${image('super-large.jpg','AMERICOL SUPER CLEANER 750 ml buteliukas',340)}</td></tr></table><p style="font-size:30px;font-weight:700;margin:0 0 16px">13,83 €</p>${cta()}</div>`,'0 24px 28px');
b+=row(`<div style="border-left:3px solid #42ba7d;padding-left:16px"><p style="color:#26744d;margin:0 0 8px;font-size:17px">★★★★★</p><p style="font-size:17px;line-height:1.5;margin:0 0 10px">Tikrai labai geras, įvairiose vietose nuvalė nešvarumus</p><a href="${url}" style="font-size:12px;color:#52635a;text-decoration:none">Evita apie SUPER CLEANER</a></div>`,'0 24px 28px');
b+=row('<div style="border:2px dashed #42ba7d;padding:20px;text-align:center"><p style="font-size:11px;letter-spacing:1px;margin:0 0 8px;font-weight:700">JUODRAŠTIS</p><h2 style="font-size:22px;margin:0 0 8px">Vieta Jūsų nuolaidai</h2><p style="font-size:13px;line-height:1.6;margin:0">Čia įrašysime patvirtintą nuolaidą, kodą ir galiojimo datą.</p></div>','0 24px 18px');
b+=row(cta(),'0 24px 28px');
b+=row('<p style="font-size:15px;line-height:1.6;margin:0 0 20px">Su meile švarai,<br><strong>PRO7 komanda</strong></p><p style="border-top:1px solid #dfe7e2;padding-top:16px;font-size:10px;line-height:1.7;color:#66736c;margin:0">Šį laišką gavote, nes užsiprenumeravote PRO7 naujienlaiškius arba esate mūsų klientas.</p>','0 24px 24px');
const html=`<!DOCTYPE html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Ne tik tai vienai dėmei. | PRO7</title><style>@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap');body{margin:0}table{border-collapse:collapse}img{border:0}</style></head><body style="margin:0;background:#ffffff"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">Baldai, batai ir plaunami paviršiai. Pažiūrėkite SUPER CLEANER rezultatus.</div><!--[if mso]><table role="presentation" width="600" align="center"><tr><td><![endif]--><table class="email" width="100%" align="center" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;max-width:600px;margin:0 auto;background:#ffffff;color:#183127;font-family:'Montserrat',Arial,sans-serif">${b}</table><!--[if mso]></td></tr></table><![endif]--></body></html>`;
fs.writeFileSync('newsletter.html',html);fs.writeFileSync('index.html',html.replaceAll(root,''));
const qa=fs.readFileSync(old+'qa.mjs','utf8').replaceAll('2026-09-22-kambariai','2026-09-25-super-cleaner');fs.writeFileSync('qa.mjs',qa);
console.log('Draft built. GIF bytes: '+fs.statSync('hero-results.gif').size);
