import {readFileSync,writeFileSync} from 'node:fs';
import sharp from '/Users/lucka/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp/dist/index.mjs';
const root=new URL('./',import.meta.url);
const publicBase='https://raw.githubusercontent.com/elaiskai/pro7-email-assets/main/nl4-prieksambario-svara/assets/';
for(const name of ['floor','super','citrus'])await sharp(new URL(`assets/${name}-original.png`,root).pathname).resize({width:536,withoutEnlargement:true}).flatten({background:'#ffffff'}).jpeg({quality:90,mozjpeg:true}).toFile(new URL(`assets/${name}.jpg`,root).pathname);
for(const name of ['before','after'])await sharp(new URL(`assets/shoes-${name}-original.jpg`,root).pathname).resize({width:650,withoutEnlargement:true}).jpeg({quality:90,mozjpeg:true}).toFile(new URL(`assets/shoes-${name}.jpg`,root).pathname);
await sharp(new URL('assets/hero-v3.png',root).pathname).resize({width:1200,withoutEnlargement:true}).jpeg({quality:90,mozjpeg:true}).toFile(new URL('assets/hero-v3.jpg',root).pathname);
const urls={floor:'https://www.pro7.lt/svaros-prekes/221-americol-floor-cleaner-1-l-grindu-valiklis-',super:'https://www.pro7.lt/svaros-prekes/113-americol-super-cleaner-0-75-l-universalus-valiklis-koncentratas',citrus:'https://www.pro7.lt/svaros-prekes/1375-floor-cleaner-citrus-1-l-grindu-valiklis',all:'https://www.pro7.lt/svaros-prekes-valikliai',home:'https://www.pro7.lt/',tools:'https://www.pro7.lt/valymo-irankiai-ir-reikmenys'};
const css=`@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap');
.pro7-nl4,.pro7-nl4 td,.pro7-nl4 p,.pro7-nl4 a,.pro7-nl4 h1,.pro7-nl4 h2{font-family:Montserrat,Arial,sans-serif}
.pro7-nl4 table{border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0}
@media(min-width:481px){.pro7-nl4 .hero-title{font-size:48px!important;line-height:51px!important}.pro7-nl4 .pad{padding-left:36px!important;padding-right:36px!important}}
@media(prefers-color-scheme:dark){.pro7-nl4,.pro7-nl4 .paper,.pro7-nl4 .soft{background:#ffffff!important;color:#182b22!important}.pro7-nl4 .label{color:#21663f!important}}
[data-ogsc] .pro7-nl4,[data-ogsc] .pro7-nl4 .paper,[data-ogsc] .pro7-nl4 .soft{background:#ffffff!important;color:#182b22!important}
`;
const table=content=>`<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="width:100%;table-layout:fixed;border-collapse:collapse">${content}</table>`;
const p=(text,extra='')=>`<p style="margin:0;font-size:15px;line-height:25px;${extra}">${text}</p>`;
const label=text=>`<p class="label" style="margin:0 0 12px;color:#21663f;font-size:11px;line-height:17px;font-weight:700;letter-spacing:1.6px">${text}</p>`;
const h2=text=>`<h2 style="margin:0 0 14px;font-size:28px;line-height:34px;font-weight:700">${text}</h2>`;
const row=(content,padding='28px 24px',bg='#ffffff',klass='paper')=>`<tr><td class="pad ${klass}" bgcolor="${bg}" style="padding:${padding};background:${bg};color:#182b22">${content}</td></tr>`;
const btn=(text,url)=>table(`<tr><td bgcolor="#42ba7d" style="background:#42ba7d;border-radius:5px;text-align:center"><a class="cta" href="${url}" style="display:block;padding:16px 8px;min-height:20px;font-size:14px;line-height:20px;font-weight:700;text-decoration:none;color:#182b22;text-align:center">${text}</a></td></tr>`);
const productImage=(key,alt,width=248)=>`<a class="product-photo" href="${urls[key]}" style="display:block;text-align:center;background:#ffffff;border-radius:8px;padding:0;margin:0 0 14px"><img src="${publicBase+key}.jpg" width="${width}" alt="${alt}" style="display:block;width:${width}px;max-width:100%;height:auto;margin:0 auto;border:0"></a>`;
const price=text=>p(text,'font-size:25px;line-height:32px;font-weight:700;margin:18px 0 16px');
const shipping=`<tr><td align="center" bgcolor="#42ba7d" style="padding:12px 16px;background:#42ba7d;color:#ffffff;text-align:center;font-size:11px;line-height:18px;font-weight:700">📦 NEMOKAMAS PRISTATYMAS LIETUVOJE <span style="white-space:nowrap">NUO 45&nbsp;€&nbsp;📦</span></td></tr>`;
const nav=table(`<tr>${[['VALIKLIAI',urls.all],['ĮRANKIAI',urls.tools],['AKCIJOS','https://www.pro7.lt/akcijos-pasiulymai']].map(([text,url])=>`<td width="33.33%" align="center" bgcolor="#ffffff" style="background:#ffffff"><a class="nav-link" href="${url}" style="display:block;padding:14px 1px;font-size:10px;line-height:16px;color:#21663f;font-weight:700;text-decoration:none;white-space:nowrap">${text}</a></td>`).join('')}</tr>`);
const header=`<tr><td bgcolor="#ffffff" style="padding:12px;background:#ffffff;border-bottom:1px solid #e3e9e2">${table(`<tr><td width="30%" valign="middle" style="padding-right:8px"><a href="${urls.home}" style="display:block;max-width:130px"><img src="${publicBase}logo.png" alt="PRO7" width="130" style="display:block;width:100%;max-width:130px;height:auto;border:0"></a></td><td width="70%" valign="middle">${nav}</td></tr>`)}</td></tr>`;
const proof=table(`<tr>${['before','after'].map((s,i)=>`<td width="50%" valign="top" style="padding:${i?'0 0 0 4px':'0 4px 0 0'}"><a href="${urls.super}" style="display:block"><img src="${publicBase}shoes-${s}.jpg" alt="Kedukai ${i?'po':'prieš'} valymą, SUPER CLEANER produkto galerijos nuotrauka" width="260" style="display:block;width:100%;height:auto;border:0"></a><p style="margin:10px 0 0;font-size:11px;line-height:16px;font-weight:700;letter-spacing:1.5px">${i?'PO':'PRIEŠ'}</p></td>`).join('')}</tr>`);

const productCard=(key,name,detail,cost)=>`<div style="margin:24px 0 0;padding:18px 0 24px;text-align:center;border:1px solid #e2e8e3;border-radius:10px;background:#ffffff">${productImage(key,name+', '+detail,170)}<h3 class="product-name" style="margin:0 12px;font-size:18px;line-height:25px;font-weight:700">${name}</h3>${p(detail,'font-size:13px;line-height:21px;margin:6px 12px 0')}${p(cost,'font-size:23px;line-height:30px;font-weight:700;margin:14px 0 18px')}<div style="max-width:340px;margin:0 auto">${btn('Rinktis '+(key==='super'?'SUPER CLEANER':key==='floor'?'FLOOR CLEANER':'CITRUS'),urls[key])}</div></div>`;
const review=(text,author)=>`<div class="product-review" style="margin:28px 0 0;padding:0 0 0 18px;border-left:3px solid #42ba7d">${label('★★★★★')}${p(text,'font-size:16px;line-height:26px;font-weight:500')}${p(author,'font-size:12px;line-height:20px;margin-top:10px;color:#627068')}</div>`;

const body=`<table role="presentation" class="pro7-nl4" align="center" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;table-layout:fixed;margin:0 auto;font-family:Montserrat,Arial,sans-serif;color:#182b22;background:#ffffff">
${shipping}${header}
<tr><td bgcolor="#ffffff" style="padding:0;background:#ffffff"><a href="${urls.floor}"><img src="${publicBase}hero-v3.jpg" width="600" alt="Lietingų dienų kasdienybė. Nusiavėte batus. Purvas liko? FLOOR CLEANER ir SUPER CLEANER. 10 % nuolaida." style="display:block;width:100%;max-width:600px;height:auto;border:0"></a></td></tr>
${row(p('Sveiki,','font-weight:600;margin-bottom:14px')+p('Lietingomis dienomis su batais namo parsinešame ir purvo. Ant kilimėlio lieka šlapi pėdsakai, ant grindų smėlis. Pirmiausia nuvalykime batus, tada išplaukime prieškambarį.'),'28px 24px')}
${row(`<section data-product="super">${label('01 / BATAI')}${h2('Dar ne laikas naujiems kedukams.')}${p('Pabandykite nuvalyti su SUPER CLEANER.')}${productCard('super','SUPER CLEANER','Universalus valiklis, 750 ml.','13,83 €')}<div class="product-proof" style="margin:36px 0 0">${label('REZULTATAS IŠ PRO7 GALERIJOS')}${proof}</div>${review('Pagaliau po grindų plovimo nesimato vaikų pėdučių, nes prieš tai ko tik nebandžiau, nors ir sausos grindys, bet vaikams prabėgus vis likdavo jų pėdutės. O dabar grindys tiesiog spindi.','Irina, SUPER CLEANER atsiliepimas')}${p('Pirmiausia išbandykite mažai matomoje vietoje ir patikrinkite tinkamumą batų medžiagai.','font-size:12px;line-height:20px;margin-top:24px;color:#627068')}</section>`,'28px 24px 40px')}
${row(`<section data-product="floor"><div style="border-top:1px solid #e2e8e3;padding-top:36px">${label('02 / GRINDYS')}${h2('Dabar grindų eilė.')}${p('Prieškambario plytelėms, laminatui ir vinilui. Koncentratą skieskite pagal etiketę.')}${productCard('floor','FLOOR CLEANER','Koncentruotas grindų valiklis, 1 l.','10,21 €')}${review('Pats geriausias grindų valiklis kokį tik teko naudoti!','Monika, FLOOR CLEANER atsiliepimas')}</div></section>`,'0 24px 40px')}
${row(`<section data-product="citrus"><div style="border-top:1px solid #e2e8e3;padding-top:36px">${label('PAGAL JŪSŲ GRINDŲ DANGĄ')}${h2('Alyvuotos ar vaškuotos grindys?')}${p('Jų priežiūrai rinkitės FLOOR CLEANER CITRUS.')}${productCard('citrus','FLOOR CLEANER CITRUS','Grindų valiklis, 1 l.','10,21 €')}</div></section>`,'0 24px 40px')}
${row(`<h2 style="margin:0 0 12px;font-size:32px;line-height:38px">Jums 10 % nuolaida</h2>${p('Pirkdami įveskite kodą:')}<p style="margin:18px 0;padding:16px;border:1px solid #a9c5b1;font-size:27px;line-height:34px;letter-spacing:3px;font-weight:700;text-align:center">KALKES</p>${p('Galioja iki rugsėjo 20 d. imtinai.','font-size:13px;line-height:21px;margin-bottom:20px')}${btn('Rinktis valymo priemones',urls.all)}`,'28px 24px','#ffffff','soft')}
${row(p('Priemones naudokite pagal etiketę ir paviršiaus priežiūros rekomendacijas.','font-size:12px;line-height:20px;margin-bottom:22px')+p('Su meile švarai,<br><strong>PRO7 komanda</strong>'),'26px 24px')}
${row(`<p class="muted" style="margin:0;font-size:10px;line-height:17px;text-align:center;color:#68756c"><a class="ink" href="${urls.home}" style="font-weight:700;text-decoration:none;color:#182b22">PRO7.LT</a> · Profesionalios švaros priemonės<br>Šį laišką gavote, nes prenumeruojate PRO7 naujienlaiškius arba esate mūsų klientas.</p>`,'22px 24px','#ffffff','soft')}
</table>`;
// Divs/sections are non-layout semantic wrappers; all geometry uses email tables and inline styles.
const fragment=body.replaceAll(/<section data-product="([^"]+)">/g,'<div data-product="$1">').replaceAll('</section>','</div>');
const head=`<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light only"><title>Nusiavėte batus. Purvas liko?</title><style>${css}</style>`;
const doc=content=>`<!doctype html><html lang="lt"><head>${head}</head><body style="margin:0;padding:0;background:#ffffff"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">Lietingomis dienomis pasirūpinkite batais ir prieškambario grindimis.</div>${content}</body></html>`;
writeFileSync(new URL('omnisend.html',root),fragment);
writeFileSync(new URL('omnisend-styles.css',root),css);
writeFileSync(new URL('index.html',root),doc(fragment.replaceAll(publicBase,'assets/')));
writeFileSync(new URL('preview-online.html',root),doc(fragment));
writeFileSync(new URL('subject.txt',root),'Nusiavėte batus. Purvas liko?\n');
writeFileSync(new URL('preheader.txt',root),'Lietingomis dienomis pasirūpinkite batais ir prieškambario grindimis.\n');
console.log('Built NL4 revision 2. Generated advertising hero; authentic product photos and proof. Missing floor proof and citrus review remain content blockers.');
